Repository yogosoda/yogosoda-project, pull requests merged in 2024-10, with the labels that each got.

#7 refactor: api class를 function 으로 변경 (YSP-55)
  README.md
  src/shared/utils/api.ts
Labels: refactor

#6 refactor: 폴더 구조 정리 및 리드미 작성 (YSP-28)
  README.md
  src/app/layout.tsx
  src/entities/index.ts
  src/shared/fonts/index.ts
  src/shared/hooks/useDebounce.ts
  src/shared/hooks/useThrottle.ts
  src/shared/icons/index.ts
  src/shared/images/index.ts
  src/shared/styles/index.css
  src/shared/styles/tailwind.css
  src/shared/utils/api.ts
  src/shared/utils/debounce.ts
  src/shared/utils/throttle.ts
  tsconfig.json
Labels: documentation, question, refactor

#8 chore: font 추가
  src/app/layout.tsx
  src/shared/fonts/NanumSquareNeo-aLt.ttf
  src/shared/fonts/NanumSquareNeo-bRg.ttf
  src/shared/fonts/NanumSquareNeo-cBd.ttf
  src/shared/fonts/NanumSquareNeo-dEb.ttf
  src/shared/fonts/NanumSquareNeo-eHv.ttf
  src/shared/fonts/index.ts
  src/shared/styles/index.css
  src/shared/styles/tailwind.css
  tailwind.config.ts
Labels: style
